---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  roles:
    - nodejs
    - golang
    - postgres

  tasks:
    - name: Install build essential
      apt:
        pkg: build-essential
        state: present
